trigger:
- main

pool:
  name: LocalHrmsAgent

steps:
- checkout: self

- script: |
    echo ===== ROOT =====
    dir
    echo ===== RECURSIVE =====
    dir /s
  displayName: "Show Full Repo Structure"