trigger:
- main

pool:
  name: LocalHrmsAgent

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: 'ZetaSaasHRMSBackend.csproj'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'ZetaSaasHRMSBackend.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: 'ZetaSaasHRMSBackend.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop